tests

diff --git a/.github/workflows/selenium.yml b/.github/workflows/selenium.yml
--- a/.github/workflows/selenium.yml
+++ b/.github/workflows/selenium.yml
@@ -61,39 +61,28 @@ jobs:
       - name: Run grep command and capture output
         id: grep
         run: |
-          grep -A 5 'Failed' TestOutput.log >> FailedTestsDesc.log
-          grep -B 1 'Failed' TestOutput.log >> FailedTests.log
-
-      - name: Run tests and capture output
-        run: |
-          echo "Result: ${{ steps.grep.outputs.RESULT }}"
+          failed_tests_desc=$(grep -A 5 'Failed' TestOutput.log || true)
+          echo "FailedTestsDesc=${failed_tests_desc}" >> $GITHUB_ENV
 
       - name: Send bug to Azure DevOps
         if: steps.tests.outcome != 'success'
-        run: |
-          failed_tests_desc=$(cat FailedTestsDesc.log)
-          echo $failed_tests_desc
-          task=$(curl -X GET -u ${{ secrets.AZURE_USERNAME }}:${{ secrets.AZURE_TOKEN }} "https://dev.azure.com/01158651/mwoProjekt/_apis/wit/wiql?api-version=6.0" -H "Content-Type: application/json" -d '{"query": "Select [System.Id] From WorkItems Where [System.WorkItemType] = \'Bug\' AND [System.Title] = \'Failed tests\'"}' | jq -r '.workItems[0].id')
-          echo $task
-          curl -X PATCH -u ${{ secrets.AZURE_USERNAME }}:${{ secrets.AZURE_TOKEN }} "https://dev.azure.com/01158651/mwoProjekt/_apis/wit/workitems/$task?api-version=7.1-preview.3" -H "Content-Type: application/json-patch+json" -d '[{"op": "add", "path": "/fields/System.Description", "value": "${failed_tests_desc}"}]'
-          curl -X PATCH -u ${{ secrets.AZURE_USERNAME }}:${{ secrets.AZURE_TOKEN }} "https://dev.azure.com/01158651/mwoProjekt/_apis/wit/workitems/$task?api-version=7.1-preview.3" -H "Content-Type: application/json-patch+json" -d '[{"op": "add", "path": "/fields/System.Title", "value": "{{ format('{0}', github.workspace + 'FailedTests.log') }}"}]'
-        # uses: fjogeleit/http-request-action@v1
-        # with:
-        #   url: "https://dev.azure.com/01158651/mwoProjekt/_apis/wit/workitems/$task?api-version=7.1-preview.3"
-        #   method: "POST"
-        #   username: ${{ secrets.AZURE_USERNAME }}
-        #   password: ${{ secrets.AZURE_TOKEN }}
-        #   customHeaders: '{"Content-Type": "application/json-patch+json"}'
-        #   data: |
-        #     [
-        #       {
-        #         "op": "add",
-        #         "path": "/fields/System.Title",
-        #         "value": "{{ format('{0}', github.workspace + 'FailedTests.log') }}"
-        #       },
-        #       {
-        #         "op": "add",
-        #         "path": "/fields/System.Description",
-        #         "value": "${failed_tests_desc}"
-        #       }
-        #     ]
+        uses: fjogeleit/http-request-action@v1
+        with:
+          url: "https://dev.azure.com/01158651/mwoProjekt/_apis/wit/workitems/$task?api-version=7.1-preview.3"
+          method: "POST"
+          username: ${{ secrets.AZURE_USERNAME }}
+          password: ${{ secrets.AZURE_TOKEN }}
+          customHeaders: '{"Content-Type": "application/json-patch+json"}'
+          data: |
+            [
+              {
+                "op": "add",
+                "path": "/fields/System.Title",
+                "value": "${{ env.FailedTestsDesc }}"
+              },
+              {
+                "op": "add",
+                "path": "/fields/System.Description",
+                "value": "${failed_tests_desc}"
+              }
+            ]
