tests

diff --git a/.github/workflows/selenium.yml b/.github/workflows/selenium.yml
--- a/.github/workflows/selenium.yml
+++ b/.github/workflows/selenium.yml
@@ -36,33 +36,15 @@ jobs:
       - uses: browser-actions/setup-chrome@latest
       - run: chrome --version
 
-      - name: Run tests
+      - name: Run tests and capture output
         id: tests
-        run: dotnet test > TestOutput.log
-        continue-on-error: true
-
-      - name: Show test output
-        uses: pCYSl5EDgo/cat@master
-        id: hello
-        with:
-          path: TestOutput.log
-      - run: echo $TEXT
-        env:
-          TEXT: ${{ steps.hello.outputs.text }}
-
-      - uses: actions/upload-artifact@v3
-        if: steps.tests.outcome != 'success'
-        with:
-          name: Log
-          path: TestOutput.log
-
-      - name: Extract failed test information
-        id: extract-info
         run: |
-          export MY_VARIABLE=$(grep -A 5 "Failed" TestOutput.log)     
+          set -e
+          dotnet test > TestOutput.log
+          TEST_OUTPUT=$(cat TestOutput.log | grep -A 3 "failed" || true)
+          echo "TEST_OUTPUT=${TEST_OUTPUT}" >> $GITHUB_ENV
 
-          
-      
+
 
       - name: Send bug to Azure DevOps
         if: steps.tests.outcome != 'success'
@@ -83,6 +65,6 @@ jobs:
                 {
                   "op": "add",
                   "path": "/fields/System.Description",
-                  "value": "${{ env.MY_VARIABLE }}"
+                  "value": "${{ env.TEST_OUTPUT }}"
                 }
               ]
